import { CalendarClock } from "lucide-react";
import type { RoadmapItem, SeoRunSummary } from "@/lib/seo/types";
import { Card, Chip, EmptyState, SectionLabel, type Tone } from "./primitives";

const HORIZONS: { key: "30" | "60" | "90"; label: string; subtitle: string }[] = [
  { key: "30", label: "First 30 days", subtitle: "Fix what is actively costing you" },
  { key: "60", label: "Days 30-60", subtitle: "Strengthen what already works" },
  { key: "90", label: "Days 60-90", subtitle: "Build for new demand" },
];

const LEVEL_TONE: Record<string, Tone> = {
  high: "good",
  medium: "warn",
  low: "muted",
};

function ItemCard({ item }: { item: RoadmapItem }) {
  return (
    <div className="rounded-lg border border-gray-200 bg-white p-3">
      <h5 className="text-[13px] font-semibold text-gray-900">{item.title}</h5>
      {item.detail ? (
        <p className="mt-1 text-[12px] leading-relaxed text-gray-600">{item.detail}</p>
      ) : null}
      <div className="mt-2 flex flex-wrap gap-1.5">
        <Chip tone={LEVEL_TONE[item.impact] ?? "muted"}>
          {item.impact} impact
        </Chip>
        <Chip tone="muted">{item.effort} effort</Chip>
      </div>
    </div>
  );
}

export function RoadmapBoard({ summary }: { summary: SeoRunSummary }) {
  const roadmap = summary.roadmap ?? [];

  if (!roadmap.length) {
    return (
      <EmptyState message="No roadmap was generated for this run. This happens when the audit finished before the analysis phase, or when there was not enough data to plan against." />
    );
  }

  return (
    <div className="space-y-4">
      <Card className="space-y-2">
        <div className="flex items-center gap-2">
          <CalendarClock size={15} className="text-gray-400" />
          <SectionLabel>How to use this plan</SectionLabel>
        </div>
        <p className="text-[12px] leading-relaxed text-gray-600">
          Actions are ordered so that the things blocking rankings are cleared first, the
          pages that already have traction are strengthened next, and new content is created
          last — building on a foundation that works rather than adding to a broken one.
        </p>
        {summary.used_ai === false ? (
          <p className="text-[11px] text-gray-500">
            This plan was generated by the built-in analyser rather than the AI model, so it
            is more formulaic. The findings it is based on are identical.
          </p>
        ) : null}
      </Card>

      <div className="grid gap-4 lg:grid-cols-3">
        {HORIZONS.map((horizon) => {
          const items = roadmap.filter((r) => r.horizon === horizon.key);
          return (
            <div key={horizon.key} className="space-y-3">
              <div className="rounded-lg bg-gray-50 px-3 py-2">
                <div className="text-[13px] font-semibold text-gray-900">
                  {horizon.label}
                </div>
                <div className="text-[11px] text-gray-500">{horizon.subtitle}</div>
              </div>
              {items.length ? (
                <div className="space-y-2">
                  {items.map((item, i) => (
                    <ItemCard key={`${item.title}-${i}`} item={item} />
                  ))}
                </div>
              ) : (
                <p className="px-1 text-[12px] text-gray-400">
                  Nothing scheduled for this window.
                </p>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
