ALTER TABLE public.process_services 
ADD COLUMN IF NOT EXISTS base_cost NUMERIC(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS base_value NUMERIC(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS estimated_days INT DEFAULT 0;

ALTER TABLE public.process_templates
ADD COLUMN IF NOT EXISTS base_price NUMERIC(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS estimated_days INT DEFAULT 0;
